from __future__ import annotations

import subprocess
from pathlib import Path

from .errors import PipelineError
from .version import DATASET_NAME, DATASET_VERSION


class ReleaseGateError(PipelineError):
    code = "release.gate_failed"


def validate_release_tag(tag: str) -> None:
    """Require the release tag to equal the dataset version tag."""
    expected = f"v{DATASET_VERSION}"
    if tag != expected:
        raise ReleaseGateError(
            f"release tag {tag!r} does not match expected release tag {expected!r}"
        )


def resolve_tag_commit(tag: str, repo_dir: Path | None = None) -> str:
    """Resolve the commit a release tag points to."""
    return _git(f"rev-parse {tag}^{{commit}}", repo_dir)


def resolve_main_commit(repo_dir: Path | None = None) -> str:
    """Resolve the commit the current main branch points to."""
    return _git("rev-parse refs/remotes/origin/main", repo_dir)


def validate_tag_at_main(tag_commit: str, main_commit: str) -> None:
    """Require a release tag to point exactly to the current main commit."""
    if tag_commit != main_commit:
        raise ReleaseGateError(
            "release tag does not point to the current main commit "
            f"(tag: {tag_commit}, main: {main_commit})"
        )


def ensure_no_existing_release(owner_repo: str, tag: str) -> None:
    """Require that no GitHub Release exists for the tag yet."""
    result = subprocess.run(
        ["gh", "release", "view", tag, "--repo", owner_repo],
        capture_output=True,
        text=True,
    )
    if result.returncode == 0:
        raise ReleaseGateError(f"GitHub Release for {tag!r} already exists in {owner_repo}")


def publish_release(owner_repo: str, tag: str, archive: Path, checksum: Path) -> None:
    """Create an immutable GitHub Release with autogenerated notes and both assets."""
    result = subprocess.run(
        [
            "gh",
            "release",
            "create",
            tag,
            "--repo",
            owner_repo,
            "--title",
            tag,
            "--generate-notes",
            str(archive),
            str(checksum),
        ],
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        raise ReleaseGateError(f"gh release create failed: {result.stderr.strip()}")


def _git(expression: str, repo_dir: Path | None) -> str:
    command = ["git", *expression.split()]
    if repo_dir is not None:
        command.extend(["-C", str(repo_dir)])
    result = subprocess.run(command, capture_output=True, text=True)
    if result.returncode != 0:
        raise ReleaseGateError(f"git {expression} failed: {result.stderr.strip()}")
    return result.stdout.strip()


__all__ = [
    "ReleaseGateError",
    "DATASET_NAME",
    "DATASET_VERSION",
    "publish_release",
]
